import { SharedFile, ActivityEvent, AdminStats } from './types';

const randomId = () => Math.random().toString(36).substring(2, 10);
const randomToken = () => Array.from({ length: 32 }, () => Math.random().toString(36).charAt(2)).join('');

export const mockFiles: SharedFile[] = [
  {
    id: 'f1a2b3c4',
    name: 'Q4-Financial-Report.pdf',
    size: 2_450_000,
    type: 'application/pdf',
    uploadedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    accessToken: 'tk_a8f2e1d0c9b4e3f7a2d1c0b9e8f7a6d5',
    expiryTimestamp: new Date(Date.now() + 22 * 60 * 60 * 1000).toISOString(),
    maxDownloads: 5,
    usedDownloads: 2,
    status: 'active',
    visibility: 'private',
    uploadedBy: 'user-1',
    uploadedByName: 'Alex Chen',
  },
  {
    id: 'g5h6i7j8',
    name: 'Product-Roadmap-2026.pptx',
    size: 8_200_000,
    type: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    uploadedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    accessToken: 'tk_b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8',
    expiryTimestamp: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
    maxDownloads: 20,
    usedDownloads: 8,
    status: 'active',
    visibility: 'private',
    uploadedBy: 'user-1',
    uploadedByName: 'Alex Chen',
  },
  {
    id: 'k9l0m1n2',
    name: 'Team-Photo-Offsite.jpg',
    size: 4_100_000,
    type: 'image/jpeg',
    uploadedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    accessToken: 'tk_c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0',
    expiryTimestamp: new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString(),
    maxDownloads: 0,
    usedDownloads: 14,
    status: 'active',
    visibility: 'public',
    uploadedBy: 'user-2',
    uploadedByName: 'Sarah Kim',
  },
  {
    id: 'o3p4q5r6',
    name: 'API-Keys-Backup.enc',
    size: 340,
    type: 'application/octet-stream',
    uploadedAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    accessToken: 'tk_d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2',
    expiryTimestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    maxDownloads: 1,
    usedDownloads: 1,
    status: 'active',
    visibility: 'private',
    uploadedBy: 'user-1',
    uploadedByName: 'Alex Chen',
  },
  {
    id: 's7t8u9v0',
    name: 'Design-System-v3.fig',
    size: 15_600_000,
    type: 'application/octet-stream',
    uploadedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    accessToken: 'tk_e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4',
    expiryTimestamp: new Date(Date.now() + 168 * 60 * 60 * 1000).toISOString(),
    maxDownloads: 0,
    usedDownloads: 3,
    status: 'active',
    visibility: 'public',
    uploadedBy: 'user-3',
    uploadedByName: 'Marcus Webb',
  },
  {
    id: 'w1x2y3z4',
    name: 'NDA-Contract-Draft.docx',
    size: 890_000,
    type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    uploadedAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    accessToken: 'tk_f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6',
    expiryTimestamp: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    maxDownloads: 3,
    usedDownloads: 0,
    status: 'revoked',
    visibility: 'private',
    uploadedBy: 'user-2',
    uploadedByName: 'Sarah Kim',
  },
];

export const mockActivity: ActivityEvent[] = [
  {
    id: '1',
    fileId: 'f1a2b3c4',
    timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    eventType: 'download_success',
    status: 'success',
    details: 'File downloaded by token holder',
  },
  {
    id: '2',
    fileId: 'f1a2b3c4',
    timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    eventType: 'download_success',
    status: 'success',
    details: 'File downloaded by token holder',
  },
  {
    id: '3',
    fileId: 'g5h6i7j8',
    timestamp: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    eventType: 'download_blocked',
    status: 'blocked',
    details: 'Download blocked – Token expired',
  },
  {
    id: '4',
    fileId: 'k9l0m1n2',
    timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    eventType: 'link_regenerated',
    status: 'info',
    details: 'Access token regenerated by owner',
  },
  {
    id: '5',
    fileId: 'f1a2b3c4',
    timestamp: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    eventType: 'access_attempt',
    status: 'success',
    details: 'Token validated successfully',
  },
  {
    id: '6',
    fileId: 's7t8u9v0',
    timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    eventType: 'download_success',
    status: 'success',
    details: 'File downloaded via public link',
  },
  {
    id: '7',
    fileId: 'o3p4q5r6',
    timestamp: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    eventType: 'download_blocked',
    status: 'blocked',
    details: 'Download blocked – Limit exceeded',
  },
  {
    id: '8',
    fileId: 'w1x2y3z4',
    timestamp: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    eventType: 'link_revoked',
    status: 'blocked',
    details: 'Link revoked by file owner',
  },
];

export const mockAdminStats: AdminStats = {
  totalUsers: 24,
  totalFiles: 156,
  activeLinks: 89,
  expiredLinks: 67,
  totalDownloads: 1_243,
  blockedAttempts: 47,
};

export function formatFileSize(bytes: number): string {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i];
}

export function formatTimeAgo(dateString: string): string {
  const diff = Date.now() - new Date(dateString).getTime();
  const minutes = Math.floor(diff / 60000);
  const hours = Math.floor(minutes / 60);
  const days = Math.floor(hours / 24);
  if (minutes < 1) return 'Just now';
  if (minutes < 60) return `${minutes}m ago`;
  if (hours < 24) return `${hours}h ago`;
  return `${days}d ago`;
}

export function formatTime(dateString: string): string {
  return new Date(dateString).toLocaleTimeString('en-US', {
    hour: 'numeric',
    minute: '2-digit',
    hour12: true,
  });
}

export function getTimeRemaining(expiryString: string): string {
  const diff = new Date(expiryString).getTime() - Date.now();
  if (diff <= 0) return 'Expired';
  const hours = Math.floor(diff / 3600000);
  const minutes = Math.floor((diff % 3600000) / 60000);
  if (hours > 24) return `${Math.floor(hours / 24)}d ${hours % 24}h`;
  if (hours > 0) return `${hours}h ${minutes}m`;
  return `${minutes}m`;
}

export type RiskLevel = 'low' | 'medium' | 'high';

export function calculateRisk(file: SharedFile): RiskLevel {
  const expiryMs = new Date(file.expiryTimestamp).getTime() - Date.now();
  const expiryHours = expiryMs / 3600000;
  const isPublic = file.visibility === 'public';
  const isUnlimited = file.maxDownloads === 0;

  if (isPublic || isUnlimited) return 'high';
  if (expiryHours > 48 || file.maxDownloads > 10) return 'medium';
  return 'low';
}

export function getFileIcon(type: string): string {
  if (type.includes('pdf')) return '📄';
  if (type.includes('image')) return '🖼️';
  if (type.includes('presentation') || type.includes('pptx')) return '📊';
  if (type.includes('word') || type.includes('document')) return '📝';
  if (type.includes('spreadsheet') || type.includes('excel')) return '📈';
  return '📁';
}

export function exportToCSV(data: Record<string, string>[], filename: string) {
  if (data.length === 0) return;
  const headers = Object.keys(data[0]);
  const csv = [
    headers.join(','),
    ...data.map(row => headers.map(h => `"${row[h] || ''}"`).join(',')),
  ].join('\n');
  const blob = new Blob([csv], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
